.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. truthcoin_qt test_truthcoin_qt
clean: FORCE
	$(MAKE) -C .. truthcoin_qt_clean test_truthcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_truthcoin_qt_check
truthcoin-qt truthcoin-qt.exe: FORCE
	 $(MAKE) -C .. truthcoin_qt
