#ifndef TRUTHCOIN_CHAINPARAMSSEEDS_H
#define TRUTHCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the truthcoin network
 * AUTOGENERATED by share/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0xc6,0xcc,0xf4,0xb2}, 59533}
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // TRUTHCOIN_CHAINPARAMSSEEDS_H
