#!/bin/bash

# This is a thin wrapper around truthcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using truthcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_TRUTHCOIND

# Grab the value of $REAL_TRUTHCOINCLI which may be truthcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_TRUTHCOINCLI}" "$@" | sed 's/\r//'
